  name: Snyk Container Vulnerability Scan - Docker Hub

  on:
    workflow_run:
      workflows: ["Build and Push Docker Image to Docker Hub and Docker Hub using VERSION file"]
      types:
        - completed

  permissions:
    contents: read
    security-events: write
    actions: read

  jobs:
    snyk-dockerhub-scan:
      name: Scan Remote Container Images with Snyk
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest

      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Read VERSION file
          id: get_version
          run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

        - name: Set lowercase image name
          id: image
          run: |
            REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            IMAGE_NAME=$(basename "${REPO_LOWER}")
            echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT
            echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

        - name: Pull and scan Docker Hub image with Snyk
          continue-on-error: true
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: oste/${{ steps.image.outputs.image_name }}:${{ steps.get_version.outputs.version }}
            args: >
              --sarif-file-output=snyk-dockerhub.sarif
              --remote

        - name: Upload Docker Hub scan results to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: snyk-dockerhub.sarif
            category: snyk/dockerhub



