name: Build and Push Docker Image to Docker Hub and GHCR using VERSION file

on:
  push:
    branches:
      - main  # Adjust if your deployment branch is different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Read VERSION file
      - name: Read VERSION file
        id: get_version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      # Generate image names
      - name: Set lowercase image names
        id: image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          NAME_ONLY=$(echo "$REPO_LOWER" | cut -d'/' -f2)
          echo "ghcr=ghcr.io/$REPO_LOWER" >> "$GITHUB_OUTPUT"
          echo "docker=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$NAME_ONLY" >> "$GITHUB_OUTPUT"

      - name: Build and Push to Docker Hub and GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.image.outputs.docker }}:${{ steps.get_version.outputs.version }}
            ${{ steps.image.outputs.docker }}:latest
            ${{ steps.image.outputs.ghcr }}:${{ steps.get_version.outputs.version }}
            ${{ steps.image.outputs.ghcr }}:latest
